### ISSUE TITLE
Rendering device is always integrated graphics

### ISSUE THREAD

**Issue by leif-motif** [Mr-Wiseguy/Zelda64Recomp#173]
**Describe the bug**
The rendering device is always the integrated graphics instead of the dedicated graphics card.

**To Reproduce**
1. Boot the game in a system with both integrated graphics and dedicated graphics.

**Expected behavior**
The decomp should select the dedicated graphics card instead of the integrated graphics for rendering.

**Screenshots**
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/140660659/8aac910d-5ae3-489d-891f-f163a9ba9105)
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/140660659/ae3736b3-4e17-4693-b1c7-17385e383c86)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version: [19045.4412]
 - CPU: [Ryzen 5 7600x]
 - GPU: [NVIDIA GeForce GTX 1650 Super]

**Additional context**
The only work-around for this issue is to boot the game while the integrated graphics are disabled.

**Comment by Marcelo20XX** [comment]
On Nvidia Control Panel you can set prefer Maximum Performance so the app can use always your dedicated graphics card

**Comment by leif-motif** [comment]
I set the option globally, and the recomp still chooses to use my integrated graphics. The recomp is also using the maximum performance setting for power, I double-checked.
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/140660659/29347113-6aa5-4579-b100-1217711f0dbe)

**Comment by DarioSamo** [comment]
RT64 will _always_ prefer the dedicated graphics card. This just sounds to me like the GPU is not visible at all to the application when you boot it. Do you have the same behavior when using Vulkan? You can edit the API on %LocalAppData%/Zelda64Recompiled/graphics.json to "Vulkan".

**Comment by leif-motif** [comment]
Changing the `api_option` field to Vulkan fixes the issue, and uses my dedicated card. I guess the Auto option causes it to pick my integrated graphics? Again, on Auto, I can force the recomp to use my dedicated card if I disable the integrated graphics, so I'm not convinced that this is an issue of no visibility.

**Comment by DarioSamo** [comment]
> Changing the `api_option` field to Vulkan fixes the issue, and uses my dedicated card. I guess the Auto option causes it to pick my integrated graphics? Again, on Auto, I can force the recomp to use my dedicated card if I disable the integrated graphics, so I'm not convinced that this is an issue of no visibility.

Interesting. I wonder if the logic itself is failing to detect the better GPU.

What Auto does is it'll pick D3D12 instead of Vulkan. Which indicates the error is only evident on the D3D12 logic so far, which sadly, both APIs give very different information as to what the devices are.

If at some point you're willing to build this yourself, then getting information from this piece of code will help out.

https://github.com/DarioSamo/RT64-HLE/blob/c144df7aae279d3a4873e919daa8f5d36d737ce3/src/d3d12/rt64_d3d12.cpp#L2906

Perhaps it's visible on the list but it's not capable of detecting which is the better GPU based on these conditions?

**Comment by leif-motif** [comment]
> If at some point you're willing to build this yourself, then getting information from this piece of code will help out.

100%. I will do so shortly here, would it be best to have this set up in Visual Studio or something where I can set a breakpoint?

Also, there seems to be a lot of freezes with Vulkan as the API backend, so I'm not sure what's going on.

**Comment by DarioSamo** [comment]
> would it be best to have this set up in Visual Studio or something where I can set a breakpoint?

Yeah, breakpointing into the code I posted and inspecting what GPU options appear will help. Building instructions have just been released [here](https://github.com/Mr-Wiseguy/Zelda64Recomp/blob/dev/BUILDING.md).

> Also, there seems to be a lot of freezes with Vulkan as the API backend, so I'm not sure what's going on.

Freezes can come from many sources so the easiest way to find out is to enabled developer mode on graphics.json and inspect with the F1 mode on the Render tab. Seeing where the spike originates will answer any questions about where the freeze probably comes from.

**Comment by leif-motif** [comment]
> Seeing where the spike originates will answer any questions about where the freeze probably comes from.

I had the render tab open the whole time, and when it froze, the freeze also carried over to the render tab as well, although there didn't appear to be a spike immediately leading to the freeze.

> Building instructions have just been released [here](https://github.com/Mr-Wiseguy/Zelda64Recomp/blob/dev/BUILDING.md).

Nice, hot-off-the-presses build instructions! I'm currently installing WSL as to build the decomp files (which is taking forever TwT), so I will update you with my results once my build environment is set up and I've inspected the GPU options.

**Comment by leif-motif** [comment]
Everything except the decomp files are built, I'm just having issues building. I set up a venv for the build, but it's complaining about this, even though I have the requirements installed. What do?
```
Traceback (most recent call last):
  File "/home/leif/git/mm/tools/fixbaserom.py", line 6, in <module>
    from libyaz0 import decompress
ModuleNotFoundError: No module named 'libyaz0'
make[1]: *** [Makefile:310: setup] Error 1
make[1]: Leaving directory '/home/leif/git/mm'
make: *** [Makefile:329: init] Error 2
```

**Comment by leif-motif** [comment]
> I had the render tab open the whole time, and when it froze, the freeze also carried over to the render tab as well, although there didn't appear to be a spike immediately leading to the freeze.

Update: switched back to the Auto api, and not only is the bug still there, but it is now crashing! Along with the crash, it took down Discord while I was in a call, so I'm starting to wonder if this is a wild goose chase because I am on a system of questionable stability. I have been having some tech issues lately, so I wonder if this entire bug is due to a malfunctioning system in general.

Would it be appropriate to close this issue until I have performed a clean Windows re-installation, just so we can rule out any misbehaving on my system's end?

**Comment by DarioSamo** [comment]
> Would it be appropriate to close this issue until I have performed a clean Windows re-installation, just so we can rule out any misbehaving on my system's end?

I think it would still be helpful to find out info about why D3D12 wasn't detecting the right GPU in the first place.

**Comment by leif-motif** [comment]
@DarioSamo Debug build has been set up (current commit at time of writing is 3f9478c7e66103ff842d023dbcdae6e8b10ced30), and the bug is still present. When both of my display adapters are active with the Auto/DX12(?) option, this is the result of inserting a breakpoint at the specified line:
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/140660659/682a7efc-b049-4da9-a831-435ecd32dc22)
With only my dedicated card active:
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/140660659/4d56649a-05cb-46bb-bf1f-c93e68e81bdc)
I've no experience doing programming with display stuff before, so all of this is greek to me.

**Comment by DarioSamo** [comment]
Add a breakpoint to this [line](https://github.com/DarioSamo/RT64-HLE/blob/c144df7aae279d3a4873e919daa8f5d36d737ce3/src/d3d12/rt64_d3d12.cpp#L2966) and tell me how many times it hits it and show me the contents of adapterDesc in the debugger.

**Comment by leif-motif** [comment]
It hits the line three times.
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/140660659/01351283-1b6e-4ee6-85d4-447e02d4af62)
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/140660659/5de4322d-9b01-4c80-a4ba-04ae2c2f1615)
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/140660659/6169c8c6-1637-4f3a-87fb-a545296f1eb5)

**Comment by DarioSamo** [comment]
Apparently your integrated graphics cards supports Raytracing while your dedicated GPU doesn't. I guess that's not good enough of a hint. :)

**Comment by DarioSamo** [comment]
I've written down the issue and it should be fixed in a future update, thank you for the help.

Now go play Quake 2 RTX with your iGPU.

**Comment by leif-motif** [comment]
> Apparently your integrated graphics cards supports Raytracing while your dedicated GPU doesn't.

I am confoosion. At least we now know what the issue was.

> I've written down the issue and it should be fixed in a future update, thank you for the help.

Glad to be of help!

**Comment by DarioSamo** [comment]
Should be fixed the next time this repository pulls RT64.

**Comment by Reonu** [comment]
I just created a PR that updates RT64 to fix this issue. If you want to play now without having to wait for 1.1.1, feel free to head [here](https://github.com/Zelda64Recomp/Zelda64Recomp/pull/316/checks) and, once the artifacts finish building (should be around 5 minutes after me publishing this comment), go to where it says "Artifact" and download the Windows artifact. This version should work correctly and pick up your dedicated GPU.

Have fun!

**Comment by leif-motif** [comment]
@Reonu I built your pull request from source, and the issue is still not fixed. I switched to the `rt64_fix_igpu_issue` branch, did an entirely clean build, and it is still picking my integrated graphics as the rendering device.

**Comment by DarioSamo** [comment]
Are you sure you updated your submodules after checking out the branch?
```
git submodule update --init --recursive
```

**Comment by leif-motif** [comment]
...Well don't I feel silly right about now. That actually applied the patch, and your pr fixes the issue on my machine.

**Comment by DarioSamo** [comment]
No worries, common mistake as git's default behavior when checking out branches is fairly silly.

**Comment by Mr-Wiseguy** [comment]
Closing as the fix that worked was incorporated into the 1.1.1 release.
